swagger: '2.0'
info:
  title: Application API
  version: '1.0.0'
  description: API for managing applications and projects
host: localhost:8080
basePath: /api/v1
schemes:
  - http
paths:
  /applications:
    post:
      summary: Create a new application
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: application
          required: true
          schema:
            $ref: '#/definitions/ApplicationCreate'
      responses:
        '201':
          description: Application created successfully
          schema:
            $ref: '#/definitions/ApplicationCreateResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: List applications
      produces:
        - application/json
      parameters:
        - in: query
          name: project
          type: string
          required: true
          description: Project name to filter applications
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              applications:
                type: array
                items:
                  $ref: '#/definitions/Application'
        '500':
          description: Internal server error
    delete:
      summary: Delete an application
      produces:
        - application/json
      parameters:
        - in: query
          name: project
          type: string
          required: true
          description: Project name containing the application
        - in: query
          name: app
          type: string
          required: true
          description: Application name to delete
      responses:
        '200':
          description: Application deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Bad request
        '404':
          description: Application not found
        '500':
          description: Internal server error

  /projects:
    post:
      summary: Create a new project
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: project
          required: true
          schema:
            $ref: '#/definitions/ProjectCreate'
      responses:
        '201':
          description: Project created successfully
          schema:
            $ref: '#/definitions/ProjectCreateResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: List all projects
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              projects:
                type: array
                items:
                  $ref: '#/definitions/ProjectInfo'
        '500':
          description: Internal server error
    delete:
      summary: Delete a project
      produces:
        - application/json
      parameters:
        - in: query
          name: project
          required: true
          type: string
          description: Name of the project to delete
      responses:
        '200':
          description: Project deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Bad request
        '404':
          description: Project not found
        '500':
          description: Internal server error

definitions:
  ApplicationCreate:
    type: object
    required:
      - project-name
      - app-name
      - app
    properties:
      project-name:
        type: string
        description: Name of the project to which the application belongs
      app-name:
        type: string
        description: Name of the application
      app:
        type: string
        description: Application specifier or repository URL

  ApplicationCreateResponse:
    type: object
    properties:
      message:
        type: string
      application:
        $ref: '#/definitions/ApplicationCreate'

  Application:
    type: object
    properties:
      project_name:
        type: string
      name:
        type: string
      dest_namespace:
        type: string
      dest_server:
        type: string

  ProjectCreate:
    type: object
    required:
      - project-name
    properties:
      project-name:
        type: string
        description: Name of the project
      labels:
        type: object
        additionalProperties:
          type: string
        description: Labels to be applied to the project
      annotations:
        type: object
        additionalProperties:
          type: string
        description: Annotations to be applied to the project

  ProjectCreateResponse:
    type: object
    properties:
      message:
        type: string
      project:
        $ref: '#/definitions/ProjectCreate'

  ProjectInfo:
    type: object
    properties:
      name:
        type: string
      namespace:
        type: string
      default_cluster:
        type: string
