### list app with specific project (indicating tenant)
GET http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2


### get app with project with not exist tennat, (should fail)
GET http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant9999

### create app with simple kustomize ref
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "application_source": {
        "repo":"https://github.com/argoproj/argocd-example-apps.git",
        "target_revision": "master",
        "path":"kustomize-guestbook",
        "submodules": true
    },
    "application_instantiation": {
        "application_name": "kustomize-guestbook3",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description"
    },
   "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ],
    "is_dryrun": false
}

### create app with simple kustomize ref with flatten mode
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "application_source": {
        "repo":"https://github.com/argoproj/argocd-example-apps.git",
        "target_revision": "master",
        "path":"kustomize-guestbook",
        "submodules": true
    },
    "application_instantiation": {
        "application_name": "kustomize-guestbook4",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description",
        "installation_mode": "flatten"
    },
   "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ],
    "is_dryrun": false
}

### create app with simple helm
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "application_source": {
        "repo": "git@github.com:apache/apisix-helm-chart.git",
        "target_revision": "master",
        "path":"charts/apisix",
        "submodules": false
    },
    "application_instantiation": {
        "application_name": "apisix",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description"
    },
   "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ],
    "is_dryrun": false
}


### argocdapplications/abcs
GET http://{{host}}:{{port}}/api/v1/deploy/applications/kustomize-guestbook1
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

### del app
DELETE http://{{host}}:{{port}}/api/v1/deploy/applications/kustomize-guestbook1
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2
