### dryrun a kustomize app (should fail)
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "is_dryrun": true,
    "application_source": {
        "repo":"git@github.com:SquidFlow/platform.git",
        "target_revision": "main",
        "path":"overlays/app/fluent-operator",
        "submodules": true
    },
    "application_instantiation": {
        "application_name": "operator-fluent-operator1",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description"
    },
   "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ]
}

### dryrun a simple kustomize app (should succeed)
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "is_dryrun": true,
    "application_source": {
        "repo":"https://github.com/argoproj/argocd-example-apps.git",
        "target_revision": "master",
        "path":"kustomize-guestbook",
        "submodules": true
    },
    "application_instantiation": {
        "application_name": "kustomize-guestbook2",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description"
    },
   "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ]
}

### dryrun a simple helm app (should succeed)
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "is_dryrun": true,
    "application_source": {
        "repo":"git@github.com:apache/apisix-helm-chart.git",
        "target_revision": "master",
        "path":"charts/apisix",
        "submodules": false
    },
    "application_instantiation": {
        "application_name": "abc",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description",
        "ingress": [
            {
                "host": "demo1.h4.com",
                "tls": {
                "enabled": true,
                    "secretName": "demo1-tls"
                }
            }
        ],
        "security": {
            "external_secret": {
                "secret_store_ref": {
                    "id": "secret-store"
                }
            }
        }
    },
    "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ]
}

### create app for dryrun for helm with multiple environments (should succeed))
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "is_dryrun": true,
    "application_source": {
        "repo":"git@github.com:SquidFlow/helm-example-app.git",
        "target_revision": "main",
        "path":"/",
        "application_specifier": {
            "helm_manifest_path": "manifests/4.0.0"
        }
    },
    "application_instantiation": {
        "application_name": "abc",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description",
        "ingress": [
            {
                "host": "demo1.h4.com",
                "tls": {
                "enabled": true,
                    "secretName": "demo1-tls"
                }
            }
        ],
        "security": {
            "external_secret": {
                "secret_store_ref": {
                    "id": "secret-store"
                }
            }
        }
    },
    "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ]
}

### create app for dryrun for kustomize (should succeed)
POST http://{{host}}:{{port}}/api/v1/deploy/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "is_dryrun": true,
    "application_source": {
        "repo":"git@github.com:SquidFlow/kustomize-example-app.git",
        "target_revision": "main",
        "path":"/"
    },
    "application_instantiation": {
        "application_name": "abc",
        "tenant_name": "tenant2",
        "appcode": "edsf",
        "description": "this application description",
        "ingress": [
            {
                "host": "demo1.h4.com",
                "tls": {
                "enabled": true,
                    "secretName": "demo1-tls"
                }
            }
        ],
        "security": {
            "external_secret": {
                "secret_store_ref": {
                    "id": "secret-store"
                }
            }
        }
    },
    "application_target": [
        {
            "cluster": "in-cluster",
            "namespace": "default"
        }
    ]
}

