### Create a SecretStore with Vault provider
POST http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

{
    "secret_store_yaml": "apiVersion: external-secrets.io/v1beta1\nkind: SecretStore\nmetadata:\n  name: vault-backend\n  namespace: default\nspec:\n  provider:\n    vault:\n      server: \"http://vault.default:8200\"\n      path: \"secret\"\n      version: \"v2\"\n      auth:\n        tokenSecretRef:\n          name: vault-token\n          key: token"
}

### List SecretStore
GET http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant2

### GET SecretStore
GET http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/58b8757a-caa2-4332-a832-cf4a6d27e5fa
Content-Type: application/json
Authorization: Bearer username@tenant2

### Update SecretStore - Update Auth and Path
PATCH http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/58b8757a-caa2-4332-a832-cf4a6d27e5fa
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

{
  "path": "secret/data/new-path",
  "auth": {
    "method": "kubernetes",
    "kubernetes": {
      "mountPath": "kubernetes",
      "role": "my-app-role",
      "serviceAccountRef": {
        "name": "my-service-account",
        "namespace": "default"
      }
    }
  }
}

### Update SecretStore - Update Server and Version
PATCH http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

{
  "server": "https://vault.example.com:8200",
  "version": "v2",
  "name": "updated-vault-store"
}

### DELETE
DELETE http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1