// Code generated by interfacer; DO NOT EDIT

package github

import (
	"context"
	"github.com/google/go-github/v43/github"
)

// PullRequests is an interface generated for "github.com/google/go-github/v43/github.PullRequestsService".
type PullRequests interface {
	Create(context.Context, string, string, *github.NewPullRequest) (*github.PullRequest, *github.Response, error)
	CreateComment(context.Context, string, string, int, *github.PullRequestComment) (*github.PullRequestComment, *github.Response, error)
	CreateCommentInReplyTo(context.Context, string, string, int, string, int64) (*github.PullRequestComment, *github.Response, error)
	CreateReview(context.Context, string, string, int, *github.PullRequestReviewRequest) (*github.PullRequestReview, *github.Response, error)
	DeleteComment(context.Context, string, string, int64) (*github.Response, error)
	DeletePendingReview(context.Context, string, string, int, int64) (*github.PullRequestReview, *github.Response, error)
	DismissReview(context.Context, string, string, int, int64, *github.PullRequestReviewDismissalRequest) (*github.PullRequestReview, *github.Response, error)
	Edit(context.Context, string, string, int, *github.PullRequest) (*github.PullRequest, *github.Response, error)
	EditComment(context.Context, string, string, int64, *github.PullRequestComment) (*github.PullRequestComment, *github.Response, error)
	Get(context.Context, string, string, int) (*github.PullRequest, *github.Response, error)
	GetComment(context.Context, string, string, int64) (*github.PullRequestComment, *github.Response, error)
	GetRaw(context.Context, string, string, int, github.RawOptions) (string, *github.Response, error)
	GetReview(context.Context, string, string, int, int64) (*github.PullRequestReview, *github.Response, error)
	IsMerged(context.Context, string, string, int) (bool, *github.Response, error)
	List(context.Context, string, string, *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error)
	ListComments(context.Context, string, string, int, *github.PullRequestListCommentsOptions) ([]*github.PullRequestComment, *github.Response, error)
	ListCommits(context.Context, string, string, int, *github.ListOptions) ([]*github.RepositoryCommit, *github.Response, error)
	ListFiles(context.Context, string, string, int, *github.ListOptions) ([]*github.CommitFile, *github.Response, error)
	ListPullRequestsWithCommit(context.Context, string, string, string, *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error)
	ListReviewComments(context.Context, string, string, int, int64, *github.ListOptions) ([]*github.PullRequestComment, *github.Response, error)
	ListReviewers(context.Context, string, string, int, *github.ListOptions) (*github.Reviewers, *github.Response, error)
	ListReviews(context.Context, string, string, int, *github.ListOptions) ([]*github.PullRequestReview, *github.Response, error)
	Merge(context.Context, string, string, int, string, *github.PullRequestOptions) (*github.PullRequestMergeResult, *github.Response, error)
	RemoveReviewers(context.Context, string, string, int, github.ReviewersRequest) (*github.Response, error)
	RequestReviewers(context.Context, string, string, int, github.ReviewersRequest) (*github.PullRequest, *github.Response, error)
	SubmitReview(context.Context, string, string, int, int64, *github.PullRequestReviewRequest) (*github.PullRequestReview, *github.Response, error)
	UpdateBranch(context.Context, string, string, int, *github.PullRequestBranchUpdateOptions) (*github.PullRequestBranchUpdateResponse, *github.Response, error)
	UpdateReview(context.Context, string, string, int, int64, string) (*github.PullRequestReview, *github.Response, error)
}
