nameOverride: "h4"
fullnameOverride: "h4"
namespace: "h4"

image:
  repository: ghcr.io/h4-poc/service
  tag: "v0.0.2"
  pullPolicy: IfNotPresent

backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 38080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  type: nginx
  className: ""
  annotations: {}
  host: h4-service.local

argocd:
  serverAddress: "argocd-server.argocd.svc.cluster.local:80"
  username: "admin"
  password: ""

applicationRepo:
  remoteUrl: "https://github.com/h4-poc/gitops.git"
  accessToken: ""
