apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: platform
    kubernetes.io/metadata.name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-operator
    app.kubernetes.io/part-of: platform
    kubernetes.io/metadata.name: external-secrets
