### Create Application Template
POST http://{{host}}:{{port}}/api/v1/applications/templates
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

{
  "name": "test-app-test1",
  "description": "test-app-template-description",
  "source": {
    "type": "git",
    "url": "https://github.com/example/mytest-app.git",
    "targetRevision": "main"
  },
  "path": "/apps/test-app",
  "owner": "team-a",
  "appType": "helm"
}

### List all Application Templates
GET http://{{host}}:{{port}}/api/v1/applications/templates
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

### GET Application Template
GET http://{{host}}:{{port}}/api/v1/applications/templates/e23dedb1-1ec8-4343-98f8-82b980e1358e
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

### Update Application Template
PATCH http://{{host}}:{{port}}/api/v1/applications/templates/e23dedb1-1ec8-4343-98f8-82b980e1358e
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1

{
  "name": "test-app-2",
  "description": "test-app-template-description"
}

### Delete Application Template
DELETE http://{{host}}:{{port}}/api/v1/applications/templates/e23dedb1-1ec8-4343-98f8-82b980e1358e
Accept: application/json
Content-Type: application/json
Authorization: Bearer username@tenant1