### create app
POST http://{{host}}:{{port}}/api/v1/applications

{
    "project-name": "testing",
    "app-name": "demo1",
    "app": "github.com/h4-poc/demo-app"
}

### get app
GET http://{{host}}:{{port}}/api/v1/applications?project=testing

### del app
DELETE http://{{host}}:{{port}}/api/v1/applications?project=testing&app=demo1

### get helm template
GET http://{{host}}:{{port}}/api/v1/helm/templates