POST http://{{host}}:{{port}}/api/v1/applications/templates

{
  "name": "test-app-template",
  "description": "test-app-template-description",
  "path": "/apps/test-app",
  "owner": "team-a",
  "source": {
    "type": "git",
    "url": "https://github.com/example/test-app.git",
    "targetRevision": "main"
  },
  "appType": "helm"
}

### List all Application Templates
GET http://{{host}}:{{port}}/api/v1/applications/templates