POST http://{{host}}:{{port}}/api/v1/deploy/argocdapplications/validate

{
    "templateSource":"git@github.com:h4-poc/platform.git",
    "targetRevision":"main",
    "path":"manifest/fluent-operator"
}