### List all clusters
GET http://{{host}}:{{port}}/api/v1/destinationCluster

### Create cluster
POST http://{{host}}:{{port}}/api/v1/destinationCluster
Content-Type: application/json

{
    "name": "sit",
    "env": "SIT",
    "kubeconfig": "xxxx-kubeconfig-with-base64",
    "labels": {
        "owner": "wgh",
        "usage": "xxx"
    }
}

### List all clusters
GET http://{{host}}:{{port}}/api/v1/destinationCluster

### Get single cluster
GET http://{{host}}:{{port}}/api/v1/destinationCluster/sit

### deregister cluster
DELETE http://{{host}}:{{port}}/api/v1/destinationCluster/sit

### Update cluster (only labels and env)
PATCH http://{{host}}:{{port}}/api/v1/destinationCluster/sit
Content-Type: application/json

{
    "env": "DEV",
    "labels": {
        "owner": "wgh",
        "usage": "xxxxxxx"
    }
}