### Create a SecretStore with Vault provider
POST http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore
Content-Type: application/json

{
    "secret_store_yaml": "apiVersion: external-secrets.io/v1beta1\nkind: SecretStore\nmetadata:\n  name: vault-backend\n  namespace: default\nspec:\n  provider:\n    vault:\n      server: \"http://vault.default:8200\"\n      path: \"secret\"\n      version: \"v2\"\n      auth:\n        tokenSecretRef:\n          name: vault-token\n          key: token"
}
