### Create a SecretStore with Vault provider
POST http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore
Content-Type: application/json

{
    "secret_store_yaml": "apiVersion: external-secrets.io/v1beta1\nkind: SecretStore\nmetadata:\n  name: vault-backend\n  namespace: default\nspec:\n  provider:\n    vault:\n      server: \"http://vault.default:8200\"\n      path: \"secret\"\n      version: \"v2\"\n      auth:\n        tokenSecretRef:\n          name: vault-token\n          key: token"
}

### List SecretStore
GET http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore

### GET SecretStore
GET http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159

### Update SecretStore - Update Auth and Path
PATCH http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159
Content-Type: application/json

{
  "path": "secret/data/new-path",
  "auth": {
    "method": "kubernetes",
    "kubernetes": {
      "mountPath": "kubernetes",
      "role": "my-app-role",
      "serviceAccountRef": {
        "name": "my-service-account",
        "namespace": "default"
      }
    }
  }
}

### Update SecretStore - Update Server and Version
PATCH http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159
Content-Type: application/json

{
  "server": "https://vault.example.com:8200",
  "version": "v2",
  "name": "updated-vault-store"
}

### DELETE
DELETE http://{{host}}:{{port}}/api/v1/security/externalsecrets/secretstore/d322eb63-91a9-45a9-9e6e-f99005d63159