[log]
level = "info"

[server]
address = "0.0.0.0"
port = 8080

[argocd]
server_address = "localhost:8080"
username = "admin"
password = "xxx"

[application_repo]
provider = ["github"]
remote_url = "https://github.com/h4-poc/application-repo.git"
access_token = "xxx"
