[server]
address = "0.0.0.0"
port = 8080

[database] # not used yet
host = "localhost"
port = 5432
username = "user"
password = "password"
dbname = "myapp"

[kubernetes] # only support two modes: `kubeconfig` and `incluster`
mode = "kubeconfig"

[kubernetes.kubeconfig]
path = "/Users/guohao/.kube/config"

[application_repo]
provider = ["github"]  # support github and bitbucket server
remote_url = "https://github.com/h4-poc/application-repo.git"
access_token = "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"
