apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
data:
  config.toml: |
    [log]
    level = "debug"

    [server]
    address = "0.0.0.0"
    port = 38080

    [argocd]
    server_address = {{ .Values.argocd.serverAddress | default "argocd-server.argocd.svc.cluster.local:80" | quote }}
    username = {{ .Values.argocd.username | default "admin" | quote }}
    password = {{ .Values.argocd.password | default "" | quote }}

    [application_repo]
    provider = ["github"]
    remote_url = {{ .Values.applicationRepo.remoteUrl | default "https://github.com/h4-poc/gitops.git" | quote }}
    access_token = {{ .Values.applicationRepo.accessToken | default "" | quote }}