# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "service-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "service-chart.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/service"]
          args: ["run", "-c", "/etc/service/config.toml"]
          ports:
            - name: http
              containerPort: 38080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/service
            - name: ssh-keys-v
              readOnly: true
                # container will see /root/.ssh/id_rsa as usual:
              mountPath: "/tmp"
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "service-chart.fullname" . }}-config
        - name: ssh-keys-v
          secret:
            secretName: ssh-keys
            defaultMode: 0600
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "service-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app/web
          command: ["node", "/app/server.js"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}