{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h4
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.type "alb" }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.type }}
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: h4-backend
            port:
              number: 38080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: h4-frontend
            port:
              number: 80
{{- end }}