# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend