name: CLI Tests

on:
  pull_request:
    paths:
      - 'pkg/**'
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/cli-test.yml'
  push:
    branches: [ main ]
    paths:
      - 'pkg/**'
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/cli-test.yml'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  test-clis:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.7'

    - name: Build CLIs
      run: |
        make build-supervisor
        make build-service

    - name: Test supervisor CLI
      run: |
        ./output/supervisor version

    - name: Test service CLI
      run: |
        ./output/service version
