name: Go Unit testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.7'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run tests with race detector
      run:  make test