name: Go Unit testing

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.7'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: make test